### ISSUE TITLE
Hehehe Level Names

### ISSUE THREAD

**Issue by xoebus** [xoebus/hahaha#2]
What can we call the different levels of "hehehe"?

**Comment by NadiDami** [comment]
I think 'he' is like 'ha'...with a twinge of dryness/apathy? 

'Hehe' is more playful. 

'Hehehe' is more mischievous...

These are quick first thoughts.

**Comment by xoebus** [comment]
![Hehehe](http://i.imgur.com/wjANVCD.jpg)
